# -*- coding: utf-8 -*-
"""ShannonB_CB.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WQco2af-5iOpVqD2RV9yqLBpYYc86l_I
"""



import pandas as pd
import math

dataT=pd.read_csv("/content/drive/MyDrive/IT262/262-CBA.csv")
print(dataT)

# set your own discount rate
discountRate=0.05

#calculate the compound discount over the years
#initialize a list of 4 elements - one for each year, 0 to 3
discountFactor=[0,0,0,0]

for year in dataT['years']:
  discountFactor[year]=1/math.pow(1+discountRate,year)

dataT['discountFactor']=[round(num,2) for num in discountFactor]
print(dataT)

#calculate Net benefit/cost for each year
NetBC=[0,0,0,0]
for year in dataT['years']:
  NetBC[year]=dataT['developmentCost'][year]+dataT['operationalCost'][year]+dataT['valueOfBenefits'][year]

dataT['NetBC']=NetBC
print(dataT)

# calculate the present value of the Net b/c for each year
# we call it NPV

#initialize another list of 4 item - one for each year
NPV=[0,0,0,0]

for year in dataT['years']:
  NPV[year]=dataT['NetBC'][year]*dataT['discountFactor'][year]

dataT['NPV']=[round(num,2) for num in NPV]
print(dataT)